# Generated by Django 6.1.1 on 2026-09-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCPFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_cds', models.CharField(db_index=True, help_text='CDS code of the district whose form was generated.', max_length=14)),
                ('district_name', models.CharField(max_length=255)),
                ('tier', models.CharField(blank=True, help_text="How the portal produced the document: 'official' when the district's own form was filled, otherwise a generated complaint letter.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucp_filings', to='tracker.incidentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
