# Generated by Django 6.1.1 on 2026-10-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_ucpfiling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolincident',
            name='school_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('secular', 'Secular'), ('private', 'Private'), ('charter', 'Charter'), ('private_religious', 'Religious/Parochial Private'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
