# Generated by Django 6.1.1 on 2026-10-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_schoolincident_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='anti_palestinian_racism_reason',
            field=models.TextField(blank=True, help_text='Why the respondent believes the incident was anti-Palestinian racism (asked on yes/maybe).'),
        ),
    ]
