# Generated by Django 6.1.1 on 2026-10-03 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_incidentreport_anti_palestinian_racism_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeidentifiedReport',
            fields=[
            ],
            options={
                'verbose_name': 'De-identified report',
                'verbose_name_plural': 'De-identified reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tracker.incidentreport',),
        ),
        migrations.CreateModel(
            name='PIIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('report_uuid', models.CharField(max_length=36)),
                ('surface', models.CharField(max_length=50)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_access_logs', to='tracker.incidentreport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PII access log entry',
                'verbose_name_plural': 'PII access log',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
