# Generated by Django 6.1.1 on 2026-10-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_incidentreport_anti_palestinian_racism_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='incident_date_estimate',
            field=models.CharField(blank=True, help_text='Free-text best estimate, used when the date precision is "Best estimate / unknown".', max_length=200),
        ),
    ]
