# Generated by Django 6.1.1 on 2026-10-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_deidentifiedreport_piiaccesslog'),
        ('tracker', '0005_incidentreport_incident_date_estimate'),
    ]

    operations = [
    ]
